MYSQL_HOST: jdbc:mysql://127.0.0.1/formbuilder_dev
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
PORT: 8090

S2S_AUTH_HEADER: Bearer b8d61620-3654-4947-b553-3fd2846c9058

UMS_HOST: 'https://ums-svc-stg.eventstrat.ai'
UMS_AUTH_HEADER: Bearer 46c7bf91-816f-4e20-8282-67ac421944fb

EMS_HOST: 'https://event-mgt-service-stg.eventstrat.ai/'
EMS_AUTH_HEADER: Bearer b8d61620-3654-4947-b553-3fd2846c9058


NOTIFICATION_HOST: 'https://notification-global-uat.eventstrat.ai'
#NOTIFICATION_HOST: 'http://localhost:8082'
NOTIFICATION_AUTH_HEADER: Bearer f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454
