package com.skt.ems.formbuilder.enums;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.skt.ems.common.error.MessageKeySource;
import jakarta.persistence.AttributeOverride;
import lombok.Getter;

@Getter
public enum MessageKey implements MessageKeySource {
    INVALID_FORM_REQ,
    NULL_OR_EMPTY_FORM_NAME,
    NULL_OR_EMPTY_FORM_COHORT,
    FORM_ALREADY_EXISTS,
    FORM_CREATED_SUCCESSFULLY,
    FORM_FETCHED_SUCCESSFULLY,
    FORM_NOT_FOUND,

    NULL_OR_EMPTY_FORM_ID,
    NULL_OR_EMPTY_USERNAME,
    FORM_RESPONSE_NOT_FOUND,
    FORM_RESPONSE_FETCHED_SUCCESSFULLY,
    FORM_RESPONSE_ALREADY_EXISTS,
    FORM_RESPONSE_CREATED_SUCCESSFULLY,
    INVALID_FORM_STATUS,
    REJECT_REASON_REQUIRED,
    FORM_RESPONSE_STATUS_UPDATED_SUCCESSFULLY,
    PUBLISHED_FORM_CAN_NOT_BE_EDITED,
    FORM_RESPONSE_STATUS_COUNT_FETCHED_SUCCESSFULLY,
    INVALID_FORM_TYPE,
    FORM_RESPONSE_EXPORTED_SUCCESSFULLY,
    FORM_RESPONSE_EXPORT_FAILED;
}
